name: CI - Sistema de Gestão de Notas

on:
  push:
  pull_request:

jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
      - name: Obter código do repositório
        uses: actions/checkout@v4

      - name: Executar testes
        run: npm test